document.getElementById('show-add-money-form').addEventListener('click',function(event){
    event.preventDefault();
    showSectionById('add-money-form');
})
document.getElementById('show-cash-out-form').addEventListener('click',function(event){
    showSectionById('cash-out-form');
})
document.getElementById('show-transaction').addEventListener('click',function(event){
    showSectionById('transaction-section');
})